const { SlashCommandBuilder, ChannelType, PermissionFlagsBits, EmbedBuilder } = require("discord.js");
const GuildConfig = require("../models/GuildConfig");
const { postVerificationMessage } = require("../modules/verificationGate");

// Safe import of the cache
const configCache = require("../utils/configCache");

/**
 * Universally clears the cache regardless of configCache.js's exact structure
 */
function safeInvalidateCache(guildId) {
  if (!configCache) return;

  if (typeof configCache.invalidateGuildConfig === "function") {
    configCache.invalidateGuildConfig(guildId);
  } else if (typeof configCache.clearCache === "function") {
    configCache.clearCache(guildId);
  } else if (typeof configCache.delete === "function") {
    configCache.delete(guildId);
  } else if (configCache instanceof Map) {
    configCache.delete(guildId);
  }
}

module.exports = {
  data: new SlashCommandBuilder()
    .setName("lotus-setup")
    .setDescription("Analyzes and automatically configures/repairs Lotus's security infrastructure.")
    .addBooleanOption((option) =>
      option
        .setName("verification")
        .setDescription("Enable the verification captcha (default: true; disable if you already have a join gate).")
        .setRequired(false)
    )
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),

  async execute(interaction) {
    try {
      if (!interaction.deferred && !interaction.replied) {
        await interaction.deferReply({ ephemeral: true });
      }

      const guild = interaction.guild;
      const enableVerification = interaction.options.getBoolean("verification") ?? true;

      let config = await GuildConfig.findOne({ guildId: guild.id });
      if (!config) {
        config = new GuildConfig({ guildId: guild.id });
      }

      const actionsTaken = [];

      // 1. Detect or create the Category
      let category = guild.channels.cache.find(
        (c) => c.type === ChannelType.GuildCategory && c.name.toLowerCase().includes("lotus")
      );

      if (!category) {
        category = await guild.channels.create({
          name: "LOTUS SECURITY",
          type: ChannelType.GuildCategory,
          permissionOverwrites: [
            { id: guild.id, deny: [PermissionFlagsBits.ViewChannel] },
            { id: guild.client.user.id, allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks, PermissionFlagsBits.ManageChannels] },
          ],
        });
        actionsTaken.push("📂 **Category:** `LOTUS SECURITY` created successfully.");
      } else {
        actionsTaken.push(`📂 **Category:** Found (<#${category.id}>).`);
      }

      // 2. Detect or create the Logs Channel
      let logChannel = config.logChannelId ? guild.channels.cache.get(config.logChannelId) : null;
      if (!logChannel) {
        logChannel = guild.channels.cache.find(
          (c) => c.type === ChannelType.GuildText && c.name === "lotus-logs" && c.parentId === category.id
        );
      }

      if (!logChannel) {
        logChannel = await guild.channels.create({
          name: "lotus-logs",
          type: ChannelType.GuildText,
          parent: category.id,
          topic: "Security logs generated by Lotus Security",
          permissionOverwrites: [
            { id: guild.id, deny: [PermissionFlagsBits.ViewChannel] },
            { id: guild.client.user.id, allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks] },
          ],
        });
        config.logChannelId = logChannel.id;
        actionsTaken.push("📜 **Logs Channel:** `#lotus-logs` created and configured.");
      } else {
        if (logChannel.parentId !== category.id) {
          await logChannel.setParent(category.id).catch(() => null);
        }
        config.logChannelId = logChannel.id;
        actionsTaken.push(`📜 **Logs Channel:** Found and verified (<#${logChannel.id}>).`);
      }

      // 3. Detect or create the Alerts Channel
      let alertChannel = config.alertChannelId ? guild.channels.cache.get(config.alertChannelId) : null;
      if (!alertChannel) {
        alertChannel = guild.channels.cache.find(
          (c) => c.type === ChannelType.GuildText && c.name === "lotus-alerts" && c.parentId === category.id
        );
      }

      if (!alertChannel) {
        alertChannel = await guild.channels.create({
          name: "lotus-alerts",
          type: ChannelType.GuildText,
          parent: category.id,
          topic: "Critical alerts sent by Lotus Security",
          permissionOverwrites: [
            { id: guild.id, deny: [PermissionFlagsBits.ViewChannel] },
            { id: guild.client.user.id, allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks] },
          ],
        });
        config.alertChannelId = alertChannel.id;
        actionsTaken.push("🚨 **Alerts Channel:** `#lotus-alerts` created and configured.");
      } else {
        if (alertChannel.parentId !== category.id) {
          await alertChannel.setParent(category.id).catch(() => null);
        }
        config.alertChannelId = alertChannel.id;
        actionsTaken.push(`🚨 **Alerts Channel:** Found and verified (<#${alertChannel.id}>).`);
      }

      // 4. Detect or create the Quarantine Role
      let quarantineRole = config.quarantineRoleId ? guild.roles.cache.get(config.quarantineRoleId) : null;
      if (!quarantineRole) {
        quarantineRole = guild.roles.cache.find((r) => r.name === "Lotus Quarantine");
      }

      if (!quarantineRole) {
        quarantineRole = await guild.roles.create({
          name: "Lotus Quarantine",
          color: "#2f3136",
          reason: "Automatic creation of the quarantine role by /lotus-setup",
        });
        config.quarantineRoleId = quarantineRole.id;
        actionsTaken.push("☣️ **Quarantine Role:** `Lotus Quarantine` created.");
      } else {
        config.quarantineRoleId = quarantineRole.id;
        actionsTaken.push(`☣️ **Quarantine Role:** Found (<@&${quarantineRole.id}>).`);
      }

      // 5. Detect or create the Quarantine Channel
      let quarantineChannel = config.quarantineChannelId ? guild.channels.cache.get(config.quarantineChannelId) : null;
      if (!quarantineChannel) {
        quarantineChannel = guild.channels.cache.find(
          (c) => c.type === ChannelType.GuildText && (c.name === "lotus-quarantine" || c.name === "🔒-quarantine") && c.parentId === category.id
        );
      }

      if (!quarantineChannel) {
        quarantineChannel = await guild.channels.create({
          name: "🔒-quarantine",
          type: ChannelType.GuildText,
          parent: category.id,
          topic: "Secure isolation space for members under Lotus Security sanctions",
          permissionOverwrites: [
            { id: guild.id, deny: [PermissionFlagsBits.ViewChannel] },
            {
              id: quarantineRole.id,
              allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.ReadMessageHistory],
              deny: [
                PermissionFlagsBits.SendMessages,
                PermissionFlagsBits.AddReactions,
                PermissionFlagsBits.CreatePublicThreads,
                PermissionFlagsBits.CreatePrivateThreads,
                PermissionFlagsBits.SendMessagesInThreads,
                PermissionFlagsBits.UseApplicationCommands,
                PermissionFlagsBits.Speak,
              ],
            },
            {
              id: guild.client.user.id,
              allow: [
                PermissionFlagsBits.ViewChannel,
                PermissionFlagsBits.SendMessages,
                PermissionFlagsBits.EmbedLinks,
                PermissionFlagsBits.ManageChannels,
              ],
            },
          ],
        });

        const infoEmbed = new EmbedBuilder()
          .setTitle("🔒 Containment Zone — Lotus Security")
          .setColor("#2b2d31")
          .setDescription(
            "**This channel is a secure isolation space.**\n\n" +
            "If you have access to this channel, your account has been placed in **automatic quarantine** following a security system trigger.\n\n" +
            "• **Restricted Access:** You cannot send messages or interact with the server.\n" +
            "• **Staff Visibility:** Administrators can identify you and review your case here.\n\n" +
            "*Please wait for an administrator to handle your case.*"
          )
          .setFooter({ text: "Lotus Security System • Restricted Zone" });

        const pinnedMsg = await quarantineChannel.send({ embeds: [infoEmbed] }).catch(() => null);
        if (pinnedMsg) await pinnedMsg.pin().catch(() => null);

        config.quarantineChannelId = quarantineChannel.id;
        actionsTaken.push("🔒 **Quarantine Channel:** `#🔒-quarantine` created under the category.");
      } else {
        if (quarantineChannel.parentId !== category.id) {
          await quarantineChannel.setParent(category.id).catch(() => null);
        }
        config.quarantineChannelId = quarantineChannel.id;
        actionsTaken.push(`🔒 **Quarantine Channel:** Found and verified (<#${quarantineChannel.id}>).`);
      }

      // 6-9. Entry verification gate (Unverified role, verification channel,
      // channel masking, verification message). Skippable via the
      // `verification:false` option — e.g. when the server already has its
      // own join gate (Discord's native onboarding, another bot, etc.) and
      // doesn't need Lotus's captcha on top of it.
      if (enableVerification) {
        // 6. Detect or create the "Unverified" Role (entry gate)
        let unverifiedRole = config.unverifiedRoleId ? guild.roles.cache.get(config.unverifiedRoleId) : null;
        if (!unverifiedRole) {
          unverifiedRole = guild.roles.cache.find((r) => r.name === "Lotus Unverified");
        }

        if (!unverifiedRole) {
          unverifiedRole = await guild.roles.create({
            name: "Lotus Unverified",
            color: "#99AAB5",
            reason: "Automatic creation of the verification role by /lotus-setup",
          });
          config.unverifiedRoleId = unverifiedRole.id;
          actionsTaken.push("🕐 **Unverified Role:** `Lotus Unverified` created.");
        } else {
          config.unverifiedRoleId = unverifiedRole.id;
          actionsTaken.push(`🕐 **Unverified Role:** Found (<@&${unverifiedRole.id}>).`);
        }

        // 7. Detect or create the Verification Channel (hidden once verified)
        let verificationChannel = config.verificationChannelId ? guild.channels.cache.get(config.verificationChannelId) : null;
        if (!verificationChannel) {
          verificationChannel = guild.channels.cache.find(
            (c) => c.type === ChannelType.GuildText && c.name === "✅-verification"
          );
        }

        // Permissions: @everyone hidden, visible ONLY to the "Lotus Unverified" role
        const verificationPermissions = [
          {
            id: guild.id,
            deny: [PermissionFlagsBits.ViewChannel], // Blocked for everyone by default (including verified members)
          },
          {
            id: unverifiedRole.id,
            allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.ReadMessageHistory], // Allowed ONLY for unverified members
            deny: [PermissionFlagsBits.SendMessages, PermissionFlagsBits.AddReactions],
          },
          {
            id: guild.client.user.id,
            allow: [
              PermissionFlagsBits.ViewChannel,
              PermissionFlagsBits.SendMessages,
              PermissionFlagsBits.EmbedLinks,
              PermissionFlagsBits.ManageMessages,
            ],
          },
        ];

        if (!verificationChannel) {
          verificationChannel = await guild.channels.create({
            name: "✅-verification",
            type: ChannelType.GuildText,
            topic: "Mandatory verification before accessing the rest of the server",
            permissionOverwrites: verificationPermissions,
          });
          config.verificationChannelId = verificationChannel.id;
          actionsTaken.push("✅ **Verification Channel:** `#✅-verification` created (restricted to unverified members).");
        } else {
          // Applies the new permissions even if the channel already existed
          await verificationChannel.permissionOverwrites.set(verificationPermissions).catch(() => null);
          config.verificationChannelId = verificationChannel.id;
          actionsTaken.push(`✅ **Verification Channel:** Found and permissions adjusted (<#${verificationChannel.id}>).`);
        }

        // 8. Hide all OTHER existing channels from the Unverified role
        const allChannels = await guild.channels.fetch();
        let protectedCount = 0;
        for (const [, ch] of allChannels) {
          if (!ch || !ch.permissionOverwrites) continue;
          if (ch.id === verificationChannel.id) continue;
          if (ch.parentId === category.id) continue;

          await ch.permissionOverwrites
            .edit(unverifiedRole.id, { ViewChannel: false }, { reason: "Lotus Verification Gate: initial masking" })
            .catch(() => null);
          protectedCount++;
        }
        actionsTaken.push(`🙈 **Masking:** ${protectedCount} existing channel(s) made invisible to unverified members.`);

        // 9. Send (or verify) the verification message with the button
        await postVerificationMessage(verificationChannel);
        actionsTaken.push("🔘 **Verification Message:** Challenge start button posted and pinned.");
      } else {
        actionsTaken.push(
          "🔕 **Entry Verification:** Skipped (`verification:false`) — no Unverified role, no verification channel, no channel masking. " +
          "Make sure your own join gate (onboarding, another bot, etc.) covers this instead."
        );
      }

      // 10. Force-enable protection & sanction modules (verification follows
      // the `verification` option chosen above instead of being forced on).
      config.antiNukeEnabled = true;
      config.antiRaidEnabled = true;
      config.antiSpamEnabled = true;
      config.altDetectionEnabled = true;
      config.verificationEnabled = enableVerification;
      config.punishment = "quarantine";

      actionsTaken.push(
        `🛡️ **Protection Systems:** \`Anti-Nuke\`, \`Anti-Raid\`, \`Anti-Spam\`, \`Anti-Alt-Detection\`${enableVerification ? ", and `Entry Verification`" : ""} **ENABLED** (Mode: Quarantine).`
      );

      // 11. Save to DB & Clear the Cache
      await config.save();
      safeInvalidateCache(guild.id);

      const embed = new EmbedBuilder()
        .setTitle("⚙️ Audit & Diagnostics /lotus-setup - Lotus")
        .setColor("#00FF7F")
        .setDescription(
          "Lotus has analyzed the server structure, realigned the configuration, and armed the security shield:\n\n" +
            actionsTaken.join("\n")
        )
        .setFooter({ text: "Lotus Security System • System armed and operational" })
        .setTimestamp();

      return interaction.editReply({ embeds: [embed] });
    } catch (error) {
      console.error("[LOTUS-SETUP ERROR]", error);
      const errorMsg = `❌ Error while running lotus-setup: \`${error.message}\``;
      if (interaction.deferred || interaction.replied) {
        return interaction.editReply({ content: errorMsg }).catch(() => null);
      } else {
        return interaction.reply({ content: errorMsg, ephemeral: true }).catch(() => null);
      }
    }
  },
};